
// This file was auto-generated by ML.NET Model Builder. 

using MLTrained_AutomobilePricePredictor;

// Create single instance of sample data from first line of dataset for model input
// The "F" stays after the numeric value
// Make the user input equal the values inside the struct
//


MLModel2.ModelInput sampleData = new MLModel2.ModelInput()
{
    Year = 2013F,
    Mileage = 19606F,
    City = @"Long Island City",
    State = @"NY",
    Make = @"Acura",
    Model = @"ILX5-Speed",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Price with predicted Price from sample data...\n\n");

Console.WriteLine($"Price: {10888F}");
Console.WriteLine($"Year: {2013F}");
Console.WriteLine($"Mileage: {19606F}");
Console.WriteLine($"City: {@"Long Island City"}");
Console.WriteLine($"State: {@"NY"}");
Console.WriteLine($"Make: {@"Acura"}");
Console.WriteLine($"Model: {@"ILX5-Speed"}");


var predictionResult = MLModel2.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Price: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

